server.port=8080

logging.level.org.springframework=DEBUG
logging.level.org.hibernate.SQL=DEBUG

spring.datasource.url=jdbc:postgresql://localhost:5432/secondhand_db
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=20MB
app.upload.advertisements-dir=uploads/advertisements